bochsDevs: bochs/bochs/gui/paramtree.cc bochs/bochs/gui/keymap.cc bochs/bochs/gui/gui.cc bochs/bochs/iodev/virt_timer.cc main.cpp
	g++ -ggdb -O0 -o bochsDevs -rdynamic -I./bochs/bochs -I./bochs/bochs/instrument/stubs -I./bochs/bochs/iodev -I./../sim/sim_pc bochs/bochs/gui/paramtree.cc bochs/bochs/gui/keymap.cc bochs/bochs/gui/gui.cc bochs/bochs/iodev/virt_timer.cc main.cpp -ldl
